name: Generate PCB Images

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install KiCad
        run: |
          sudo add-apt-repository ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt install -y kicad kicad-common --no-install-recommends

      - name: Generate images
        run: |
          kicad-cli pcb render nimbus-core.kicad_pcb \
          --output isometric_top.png \
          --quality high \
          --width 2000 \
          --height 2000 \
          --zoom 0.9 \
          --rotate 315,0,45
          kicad-cli pcb render nimbus-core.kicad_pcb \
          --output isometric_bottom.png \
          --quality high \
          --width 2000 \
          --height 2000 \
          --zoom 0.9 \
          --rotate 315,180,135

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add isometric_top.png isometric_bottom.png
          git commit -m "Update PCB images" || echo "No changes"
          git push
